apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: step-eks-cluster
  region: ap-south-1

vpc:
  id: "vpc-0153bddde781a802e"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      ap-south-1c: { id: subnet-035288a306162c1d9 }
      ap-south-1a: { id: subnet-0a014b72f17388994 }
      ap-south-1b: { id: subnet-0166c6a13be59894a }

managedNodeGroups:
  - name: ng-db
    instanceType: t3.small
    labels: { role: builders }
    minSize: 2
    maxSize: 4
    ssh: 
      allow: true #will use ~/.ssh/id_rsa.pub as the default ssh key
    tags:
      Name: ng-db
  - name: ng-spot
    instanceType: t3.medium
    labels: { role: builders }
    minSize: 3
    maxSize: 6
    spot: true
    ssh: 
      allow: true #will use ~/.ssh/id_rsa.pub as the default ssh key
    tags:
      Name: ng-spot
